baseURL = "https://tuxy-streamer.github.io/blog/"
languageCode = "en-us"
title = "Tuxy's Blog"
theme = "PaperMod"
timeZone = "Asia/Kolkata"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[params]
author = "Tuxy"
dateFormat = "January 2, 2006"
ShowReadingTime = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowPostNavigationLinks = true
ShowCodeCopyButtons = true
comments = true
ShowWordCount = true
ShowFullTextInRSS = true
ShowRssButtonInSectionTermList = true
showRecentPosts = true
recentPostsCount = 10

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="tuxy-streamer/blog"
        data-repo-id="R_kgDONC17xg"
        data-category="General"
        data-category-id="DIC_kwDONC17xs4Cplf5"
        data-mapping="pathname"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="gruvbox_dark"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""

[pagination]
pagerSize = 10

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 40

[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archive/"
weight = 50

[[menu.main]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"
weight = 60

[[menu.main]]
identifier = "Me"
name = "Me"
url = "/me/"
weight = 70
